version: 2

models:
  - name: store_sales_cleaned
    columns:
      - name: STORE_NUMBERS
        tests:
          - not_null
      - name: BOOK_NAME
        tests:
          - not_null
      - name: AUTHORS
        tests:
          - not_null