{{ config(materialized = 'table', schema = "STAGING") }}

SELECT 
    CAST(CREATED_AT AS DATE) AS "SNAPSHOT_DATE"
	,STORE_NUMBER 
	,STORE_NAME 
	,AREA_NUMBER
	,AREA_NAME 
	,ISBN AS "BOOK_ISBN"
	,SPLIT(TRIM(COALESCE(AUTHOR, 'Unknown Author')), ';') AS "AUTHORS"
	,TITLE AS "BOOK_NAME"
	,PUBLISHER AS "PUBLISHER_NAME"
	,IMPRINT AS "PUBLISHER_IMPRINT"
	,AVAILABILITY 
	,RRP AS "PRICE"
	,CORE_STOCK_FLAG 
	,PUBLICATION_DATE 
	,TRIM(PRODUCT_GROUP) AS "PRODUCT_GROUP"
	,TRIM(DEPARTMENT) AS "DEPARTMENT"
	,TRIM(SUB_DEPARTMENT) AS "SUB_DEPARTMENT"
	,TRIM(CLASS) AS "CLASS"
	,QTY_ON_HAND AS "AVAILABLE_STOCK"
	,QTY_ON_ORDER AS "ORDERS_REQUESTED"
	,QTY_RECEIVED AS "ORDERS_RECIEVED"
	,QTY_RETURNED AS "QTY_REFUNDED"
	,CASE WHEN QTY_SOLD < 0 THEN 0 ELSE QTY_SOLD END AS "QTY_SOLD"
	,HUB_QTY_ON_HAND 
	,HUB_QTY_ON_ORDER
    ,CREATED_AT 
	,UPDATED_AT 
FROM {{ source('raw', 'store_sales') }}

